Initial scratch of the NetBSD support

diff --git a/utils/build-script-impl b/utils/build-script-impl
--- a/utils/build-script-impl
+++ b/utils/build-script-impl
@@ -11,6 +11,8 @@
 #
 #===------------------------------------------------------------------------===#
 
+set -x
+
 #
 # This script is an implementation detail of other build scripts and should not
 # be called directly.
@@ -106,6 +108,7 @@ KNOWN_SETTINGS=(
     skip-build-swift            ""               "set to skip building Swift"
     skip-build-linux            ""               "set to skip building Swift stdlibs for Linux"
     skip-build-freebsd          ""               "set to skip building Swift stdlibs for FreeBSD"
+    skip-build-netbsd           ""               "set to skip building Swift stdlibs for NetBSD"
     skip-build-cygwin           ""               "set to skip building Swift stdlibs for Cygwin"
     skip-build-osx              ""               "set to skip building Swift stdlibs for OSX"
     skip-build-ios              ""               "set to skip building Swift stdlibs for iOS"
@@ -134,6 +137,7 @@ KNOWN_SETTINGS=(
     skip-test-libdispatch       ""               "set to skip testing libdispatch"
     skip-test-linux             ""               "set to skip testing Swift stdlibs for Linux"
     skip-test-freebsd           ""               "set to skip testing Swift stdlibs for FreeBSD"
+    skip-test-netbsd            ""               "set to skip testing Swift stdlibs for NetBSD"
     skip-test-cygwin            ""               "set to skip testing Swift stdlibs for Cygwin"
     skip-test-osx               ""               "set to skip testing Swift stdlibs for OSX"
     skip-test-ios               ""               "set to skip testing Swift stdlibs for iOS"
@@ -245,6 +249,9 @@ function set_deployment_target_based_options() {
             SWIFT_HOST_VARIANT_ARCH="aarch64"
             ;;
         freebsd-x86_64)
+            SWIFT_HOST_VARIANT_ARCH="x86_64"
+            ;;
+        netbsd-x86_64)
             SWIFT_HOST_VARIANT_ARCH="x86_64"
             ;;
         linux-powerpc64)
@@ -445,6 +452,8 @@ function set_deployment_target_based_options() {
 # If the Mac's bash were not stuck in the past, we could "declare -A" an
 # associative array, but instead we have to hack it by defining variables
 # declare -A IS_KNOWN_SETTING
+
+exit 1
 for ((i = 0; i < ${#KNOWN_SETTINGS[@]}; i += 3)); do
     setting="${KNOWN_SETTINGS[i]}"
 
@@ -452,7 +461,7 @@ for ((i = 0; i < ${#KNOWN_SETTINGS[@]}; i += 3)); do
 
     varname="$(to_varname "${setting}")"    # upcase the setting name to get the variable
     eval "${varname}_IS_KNOWN_SETTING=1"
-
+    echo "${varname}_IS_KNOWN_SETTING=1"
     if [[ "${default_value}" ]] ; then
         # For an explanation of the backslash see http://stackoverflow.com/a/9715377
         eval ${varname}=$\default_value
@@ -527,9 +536,9 @@ while [[ "$1" ]] ; do
             # check to see if this is a known option
             known_var_name="${varname}_IS_KNOWN_SETTING"
             if [[ ! "${!known_var_name}" ]] ; then
-                echo "Error: Unknown setting: ${setting}" 1>&2
-                usage 1>&2
-                exit 1
+#                echo "Error: Unknown setting: ${setting}" 1>&2
+#                usage 1>&2
+#                exit 1
             fi
 
             # find the intended value
@@ -811,6 +820,12 @@ case "$(uname -s -m)" in
         )
         ;;
 
+    NetBSD\ amd64)
+        STDLIB_DEPLOYMENT_TARGETS=(
+            "netbsd-x86_64"
+        )
+        ;;
+
     CYGWIN_NT-10.0\ x86_64)
         STDLIB_DEPLOYMENT_TARGETS=(
             "cygwin-x86_64"
@@ -918,6 +933,10 @@ for deployment_target in "${STDLIB_DEPLOYMENT_TARGETS[@]}"; do
         freebsd-*)
             build_for_this_target=$(not ${SKIP_BUILD_FREEBSD})
             test_this_target=$(not ${SKIP_TEST_FREEBSD})
+            ;;
+        netbsd-*)
+            build_for_this_target=$(not ${SKIP_BUILD_NETBSD})
+            test_this_target=$(not ${SKIP_TEST_NETBSD})
             ;;
         cygwin-*)
             build_for_this_target=$(not ${SKIP_BUILD_CYGWIN})
@@ -1709,6 +1728,24 @@ for deployment_target in "${HOST_TARGET}" "${CROSS_TOOLS_DEPLOYMENT_TARGETS[@]}"
                             "${LLDB_SOURCE_DIR}"
                         )
                         ;;
+                    NetBSD)
+                        cmake_options=(
+                            "${cmake_options[@]}"
+                            -DCMAKE_BUILD_TYPE:STRING="${LLDB_BUILD_TYPE}"
+                            -DCMAKE_INSTALL_PREFIX:PATH="${INSTALL_PREFIX}"
+                            -DLLDB_PATH_TO_LLVM_SOURCE:PATH="${LLVM_SOURCE_DIR}"
+                            -DLLDB_PATH_TO_CLANG_SOURCE:PATH="${CLANG_SOURCE_DIR}"
+                            -DLLDB_PATH_TO_SWIFT_SOURCE:PATH="${SWIFT_SOURCE_DIR}"
+                            -DLLDB_PATH_TO_LLVM_BUILD:PATH="${llvm_build_dir}"
+                            -DLLDB_PATH_TO_CLANG_BUILD:PATH="${llvm_build_dir}"
+                            -DLLDB_PATH_TO_SWIFT_BUILD:PATH="${swift_build_dir}"
+                            -DLLDB_PATH_TO_CMARK_BUILD:PATH="${cmark_build_dir}"
+                            -DLLDB_IS_BUILDBOT_BUILD="${LLDB_IS_BUILDBOT_BUILD}"
+                            -DLLDB_BUILD_DATE:STRING="\"${LLDB_BUILD_DATE}\""
+                            -DLLDB_ALLOW_STATIC_BINDINGS=1
+                            "${LLDB_SOURCE_DIR}"
+                        )
+                        ;;
                     CYGWIN_NT-10.0)
                         cmake_options=(
                             "${cmake_options[@]}"
@@ -1921,7 +1958,7 @@ tests_busted ()
 
 for deployment_target in "${STDLIB_DEPLOYMENT_TARGETS[@]}"; do
     case ${deployment_target} in
-        linux-* | freebsd-* | macosx-* | cygwin-*)
+        linux-* | freebsd-* | macosx-* | cygwin-* | netbsd-*)
             # OK, we can run tests directly.
             ;;
         iphoneos-* | iphonesimulator-* | appletvos-* | appletvsimulator-* | watchos-* | watchsimulator-*)
@@ -2162,6 +2199,8 @@ for deployment_target in "${HOST_TARGET}" "${CROSS_TOOLS_DEPLOYMENT_TARGETS[@]}"
                         ;;
                     FreeBSD)
                         ;;
+                    NetBSD)
+                        ;;
                     CYGWIN_NT-10.0)
                         ;;
                     Darwin)
@@ -2205,6 +2244,10 @@ for deployment_target in "${HOST_TARGET}" "${CROSS_TOOLS_DEPLOYMENT_TARGETS[@]}"
                 fi
                 if [[ $(uname -s) == "FreeBSD" ]]; then
                     LIB_TARGET="freebsd"
+                    ARCH_FLAG="--arch=\"${SWIFT_HOST_VARIANT_ARCH}\""
+                fi
+                if [[ $(uname -s) == "NetBSD" ]]; then
+                    LIB_TARGET="netbsd"
                     ARCH_FLAG="--arch=\"${SWIFT_HOST_VARIANT_ARCH}\""
                 fi
                 if [[ $(uname -s) == "CYGWIN_NT-10.0" ]]; then
